### ISSUE TITLE
Is the MRR calculation reasonable now?

### ISSUE THREAD

**Issue by fengzhangyin** [github/CodeSearchNet#91]
CodeSearchNet is a very good task. I think this will greatly promote the development of this field.
But I have some questions, as follows:
1. The MRR and NDCG performances are inconsistent.  The model has a high MRR value on test sets, but has a low score on the leaderboard. Why is that?
2. According to my understand, the calculation of MRR is based on the order in a batch.  However, the examples in the batch are random and the batch size affects the calculation of the MRR. Is this appropriate?
3. If I want to train a model, how should I evaluate the model and select the best model during training?  Is there a better way ?

**Comment by mallamanis** [comment]
Hi @fengzhangyin 

CodeSearchNet has two tasks:

a) Given a documentation comment (e.g. Python docstring) try to find the original code snippet that matches that comment. For this task, there is plenty of data and thus supervised machine learning methods can be used to train models.
  * During training, we randomize the batch elements and ask the model to learn to pick the correct code from within the batch.
  * During validation/testing, the batch elements are fixed (given that the evaluation dataset doesn't change) and therefore comparing among models is possible.
  * We train our models using the MRR objective using a fixed validation ordering and batch size.

b) However, documentation comments are not necessarily representative of real code search queries. For this reason we have collected a small dataset of human-collected annotations (which is hidden behind the leaderboard submission). 
  * Relevance annotations are commonly evaluated using NDCG. MRR does not apply.
  * The ability to rank the correct snippet highly, does not necessarily correlate with NDCG/human-relevance annotations since documentation comments differ from search queries.

_How should you train the model?_ That's up to you. We suggest using MRR and the docstring<->code task, but feel free to pick any alternative you think it would work best. _How do you pick the best model?_ Again it's up to you. 

Have a look at the [Technical Report](https://arxiv.org/abs/1909.09436) for more info.

**Comment by fengzhangyin** [comment]
Hi @mallamanis 
Thank you very much. The explanation is very clear.
